# Generated by Django 5.0.7 on 2024-08-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Provience 5', 'Provience 5'), ('Provience 1', 'Provience 1'), ('Provience 4', 'Provience 4'), ('Provience 6', 'Provience 6'), ('Provience 3', 'Provience 3'), ('Provience 2', 'Provience 2'), ('Provience 7', 'Provience 7')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Provience 5', 'Provience 5'), ('Provience 1', 'Provience 1'), ('Provience 4', 'Provience 4'), ('Provience 6', 'Provience 6'), ('Provience 3', 'Provience 3'), ('Provience 2', 'Provience 2'), ('Provience 7', 'Provience 7')], default='Pending', max_length=50)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OderPlaced',
        ),
    ]
