# Generated by Django 5.0.7 on 2024-08-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_state_orderplaced_delete_oderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Provience 3', 'Provience 3'), ('Provience 7', 'Provience 7'), ('Provience 4', 'Provience 4'), ('Provience 1', 'Provience 1'), ('Provience 6', 'Provience 6'), ('Provience 2', 'Provience 2'), ('Provience 5', 'Provience 5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Provience 3', 'Provience 3'), ('Provience 7', 'Provience 7'), ('Provience 4', 'Provience 4'), ('Provience 1', 'Provience 1'), ('Provience 6', 'Provience 6'), ('Provience 2', 'Provience 2'), ('Provience 5', 'Provience 5')], default='Pending', max_length=50),
        ),
    ]
